// Auto-generated by scripts/build-graph-data.js — do not edit by hand.
// Source: memory/index/latest.json (generated 2026-08-11T20:23:37.031Z)
window.JARVIS_GRAPH_DATA = {
  "generatedAt": "2026-08-11T20:23:37.031Z",
  "foldersConfigured": [
    "/home/claude/jarvis/demo-data"
  ],
  "totalFilesFound": 8,
  "countsByExtension": {
    ".md": 4,
    ".txt": 3,
    ".json": 1
  },
  "graph": {
    "nodes": [
      {
        "id": "/home/claude/jarvis/demo-data/notes/project_alpha.md",
        "name": "project_alpha.md",
        "ext": ".md",
        "category": "notes",
        "degree": 3
      },
      {
        "id": "/home/claude/jarvis/demo-data/notes/random_idea.txt",
        "name": "random_idea.txt",
        "ext": ".txt",
        "category": "notes",
        "degree": 0
      },
      {
        "id": "/home/claude/jarvis/demo-data/notes/sample.json",
        "name": "sample.json",
        "ext": ".json",
        "category": "notes",
        "degree": 1
      },
      {
        "id": "/home/claude/jarvis/demo-data/meetings/meeting_2026_02_10.md",
        "name": "meeting_2026_02_10.md",
        "ext": ".md",
        "category": "meetings",
        "degree": 4
      },
      {
        "id": "/home/claude/jarvis/demo-data/invoices/invoice_acme_001.txt",
        "name": "invoice_acme_001.txt",
        "ext": ".txt",
        "category": "invoices",
        "degree": 3
      },
      {
        "id": "/home/claude/jarvis/demo-data/invoices/invoice_beta_002.txt",
        "name": "invoice_beta_002.txt",
        "ext": ".txt",
        "category": "invoices",
        "degree": 1
      },
      {
        "id": "/home/claude/jarvis/demo-data/clients/acme_co.md",
        "name": "acme_co.md",
        "ext": ".md",
        "category": "clients",
        "degree": 4
      },
      {
        "id": "/home/claude/jarvis/demo-data/clients/beta_industries.md",
        "name": "beta_industries.md",
        "ext": ".md",
        "category": "clients",
        "degree": 2
      }
    ],
    "edges": [
      [
        "/home/claude/jarvis/demo-data/notes/project_alpha.md",
        "/home/claude/jarvis/demo-data/meetings/meeting_2026_02_10.md"
      ],
      [
        "/home/claude/jarvis/demo-data/notes/project_alpha.md",
        "/home/claude/jarvis/demo-data/invoices/invoice_acme_001.txt"
      ],
      [
        "/home/claude/jarvis/demo-data/notes/project_alpha.md",
        "/home/claude/jarvis/demo-data/clients/acme_co.md"
      ],
      [
        "/home/claude/jarvis/demo-data/meetings/meeting_2026_02_10.md",
        "/home/claude/jarvis/demo-data/invoices/invoice_acme_001.txt"
      ],
      [
        "/home/claude/jarvis/demo-data/meetings/meeting_2026_02_10.md",
        "/home/claude/jarvis/demo-data/clients/acme_co.md"
      ],
      [
        "/home/claude/jarvis/demo-data/meetings/meeting_2026_02_10.md",
        "/home/claude/jarvis/demo-data/clients/beta_industries.md"
      ],
      [
        "/home/claude/jarvis/demo-data/invoices/invoice_acme_001.txt",
        "/home/claude/jarvis/demo-data/clients/acme_co.md"
      ],
      [
        "/home/claude/jarvis/demo-data/clients/acme_co.md",
        "/home/claude/jarvis/demo-data/notes/sample.json"
      ],
      [
        "/home/claude/jarvis/demo-data/clients/beta_industries.md",
        "/home/claude/jarvis/demo-data/invoices/invoice_beta_002.txt"
      ]
    ]
  }
};
